title: Absolute Value
logo: /assets/img/absolutevaluelogo.png
description: A podcast about applied math, investing, and the essential underlying principles that help us live happy, healthy, and productive lives. Hosted by Daniel Ling.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
