title: Absolute Value with Daniel Ling
logo: /assets/img/logo 2.png
description: A podcast about applied math, investing, and the essential underlying principles that help us live happy, healthy, and productive lives. Hosted by Daniel Ling.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
